rm(list = ls())
invisible(lapply(readLines('./Maps/dependencies.txt'), library, character.only = T))
invisible(lapply(paste0("./Helpers/", list.files("./Helpers")), source))
invisible(lapply(c('./App/server.R', './App/ui.R'), source))
shinyApp(ui, server)